# Generated by Django 5.2.11 on 2026-02-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "Employee_Id",
                    models.CharField(
                        default="UNDEFINED",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("Full_name", models.CharField(max_length=150)),
                ("Email_Field", models.EmailField(max_length=254, unique=True)),
                ("Departments", models.CharField(max_length=100)),
            ],
        ),
    ]
